# Generated by Django 3.2.4 on 2021-07-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('stylist_notes', models.TextField(blank=True)),
                ('selling_price', models.IntegerField(blank=True)),
                ('discount', models.IntegerField(blank=True)),
                ('image', models.CharField(blank=True, max_length=2000)),
                ('additional_info', models.TextField(blank=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
